### ISSUE TITLE
Image from camera 2 is stripped

### ISSUE THREAD

**Issue by eboudrand** [ivmech/ivport-v2#16]
I have a problem with an IVPort V2 quad multiplexer. Image from camera 2 is always stripped. I have changed the  ribbon cable and the result is still the same. The image from camera 2 looks similar than image from camera 1. 

My Python code is : 

#!/usr/bin/env python

import ivport

iv = ivport.IVPort(ivport.TYPE_QUAD2, iv_jumper='A')

iv.camera_open(camera_v2=True, resolution=(640,480))
iv.camera_change(1)
iv.camera_capture("picam", use_video_port=False)
iv.camera_change(2)
iv.camera_capture("picam", use_video_port=False)
iv.camera_change(3)
iv.camera_capture("picam", use_video_port=False)
iv.camera_change(4)
iv.camera_capture("picam", use_video_port=False)
iv.close()

I uploaded images taken with the multiplexer :
Camera 1
![picam_cam1](https://user-images.githubusercontent.com/6330590/50512526-b0400780-0a92-11e9-93bd-ea6d3906b19b.jpg)
Camera 2
![picam_cam2](https://user-images.githubusercontent.com/6330590/50512529-b7ffac00-0a92-11e9-987b-59185577c7fa.jpg)
Camera 3
![picam_cam3](https://user-images.githubusercontent.com/6330590/50512532-bd5cf680-0a92-11e9-951c-3d1ca4c54a1e.jpg)
Camera 4
![picam_cam4](https://user-images.githubusercontent.com/6330590/50512542-d5cd1100-0a92-11e9-8aa0-e2cae345ff3f.jpg)

**Comment by eboudrand** [comment]
The card was faulty. I finally got a replacement card from Ivmech a month later. Now it is worst : no images ! Logs report an issue met by other users :
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/home/pi/ivport-v2/picamera/camera.py", line 129, in
_control_callback
    "Received unexpected camera control callback event, 0x%08x" %
buf[0].cmd)
picamera.exc.PiCameraRuntimeError: Received unexpected camera control
callback event, 0x4f525245
Traceback (most recent call last):
  File "essai.py", line 9, in <module>
    iv.camera_capture("picam", use_video_port=False)
  File "/home/pi/ivport-v2/ivport.py", line 142, in camera_capture
    self.picam.capture(filename + "_CAM" + str(self.camera) + '.jpg',
**options)
  File "/home/pi/ivport-v2/picamera/camera.py", line 1619, in capture
    'Timed out waiting for capture to end')
picamera.exc.PiCameraRuntimeError: Timed out waiting for capture to end
```

**Comment by leoshmu** [comment]
I have the same issue with striped images! I am using an ivport dual v2 on a raspberry pi 3 - camera2 always gives an image with stripes. @eboudrand, how did you determine that the board was faulty? Is the stripes enough to indicate that the board must be replaced or is there some other trouble shooting that you did to figure out that there was a fault with the board?

![image](https://user-images.githubusercontent.com/704898/107094188-367bbb80-67cc-11eb-9167-90c4900cae60.png)

**Comment by eboudrand** [comment]
@leoshmu I gave up with this issue. I don't remember what I did about it. I think I swapped the cameras and I have also checked the ports one by one by using only one camera at the same time. I can look at this issue again at the end of the week.

**Comment by leoshmu** [comment]
> @leoshmu I gave up with this issue. I don't remember what I did about it. I think I swapped the cameras and I have also checked the ports one by one by using only one camera at the same time. I can look at this issue again at the end of the week.

Thank you - I think unfortunately this board is not very reliable - I've asked multiple questions from the developer and there is no response. I'm going to try other providers like arducam or even the pi 4 compute module which has 2 CSI ports built in. I would be happy to give this a chance if there was some help provided by the developer

**Comment by polytec22** [comment]
I was getting the same issue. Just turned off everything and connected the camera ribbon cable and sunny connector again which seems to have fixed the issue. Hope this helps.

**Comment by leoshmu** [comment]
@polytec22 thanks, I tried that before as well but will try again. It's a bit frustrating to have a board that doesn't work reliably every time but I'll give it another try
