### ISSUE TITLE
Unable to run test script

### ISSUE THREAD

**Issue by weirdgyn** [ivmech/ivport-v2#23]
Hallo, I bought one of your board to use in a project I followed your installation instructions but when I run the scripts to check the whole thing I got this error:

```
pi@raspberrypi:~/ivport-v2 $ python init_ivport.py 
pi@raspberrypi:~/ivport-v2 $ python test_ivport.py 
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/home/pi/ivport-v2/picamera/camera.py", line 129, in _control_callback
    "Received unexpected camera control callback event, 0x%08x" % buf[0].cmd)
picamera.exc.PiCameraRuntimeError: Received unexpected camera control callback event, 0x4f525245

Traceback (most recent call last):
  File "test_ivport.py", line 60, in <module>
    main()
  File "test_ivport.py", line 56, in main
    picam_capture()
  File "test_ivport.py", line 33, in picam_capture
    iv.camera_capture("picam", use_video_port=False)
  File "/home/pi/ivport-v2/ivport.py", line 142, in camera_capture
   self.picam.capture(filename + "_CAM" + str(self.camera) + '.jpg', **options)
  File "/home/pi/ivport-v2/picamera/camera.py", line 1617, in capture
    if not encoder.wait(self.CAPTURE_TIMEOUT):
  File "/home/pi/ivport-v2/picamera/encoders.py", line 848, in wait
    result = self.event.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 614, in wait
    self.__cond.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)

```

Do you have an idea about where the problem should be?
BTW I checked the board and found that SEL signal is correctly feed to SEL pin on MIPI mux but not on A0 pin I2C mux.
I'm using two identical RaspiCAM V2 modules in my setup.

Best regards,
 weirdgyn

**Comment by weirdgyn** [comment]
The issue seems to be related to the wrong management of i2c interface. Camera i2c bus and raspberry user i2c bus aren't the same bus but in this board such connection are connected creating de-facto a multimaster topolgy that camera module isn't able to manage.
